dist: trusty

# Use containers instead of full VMs for faster startup.
sudo: false

matrix:
    fast_finish: true

language: python
python:
  # - "2.6"
  - "2.7"
  # - "3.2"
  # - "3.3"
  # - "3.4"
  - "3.5"
  # - "3.5-dev" # 3.5 development branch
  # - "3.6"
  # - "3.6-dev" # 3.6 development branch
  # - "3.7-dev" # 3.7 development branch
  # - "nightly"

# command to install dependencies
install:
  - travis_retry pip install -r requirements.txt
  - travis_retry pip install codecov

# command to run tests
script:
  - pytest
  # make coverage reports for Codecov to find
  - if [[ $TRAVIS_PYTHON_VERSION != nightly ]]; then coverage xml; fi

after_success:
    # call codecov from project root
    - if [[ $TRAVIS_PYTHON_VERSION != nightly ]]; then cd ../ && codecov; fi
